title       = Minetest Classic Plus
description = A classic sandbox game built on the Minetest Classic foundation.
# TODO readd singlenode when the mainmenu handles priority right
allowed_mapgens = v6
min_minetest_version = 5.6
